"""Pydantic models for Bible data."""

from pydantic import BaseModel


class Verse(BaseModel):
    """A single Bible verse."""
    id: int | None = None
    book: str
    chapter: int
    verse: int
    reference: str
    text: str
    translation: str = "KJV"
    embedding: list[float] | None = None


class Book(BaseModel):
    """Bible book metadata."""
    id: int | None = None
    name: str
    abbreviation: str
    testament: str  # "OT" or "NT"
    position: int  # 1-66
    chapters: int
    verses: int
    # Enriched fields (generated by LLM)
    author: str | None = None
    date_written: str | None = None
    audience: str | None = None
    theme: str | None = None
    summary: str | None = None
    outline: list[str] | None = None
    key_verses: list[str] | None = None


class Chapter(BaseModel):
    """Bible chapter with summary."""
    id: int | None = None
    book: str
    chapter: int
    verse_count: int
    # Enriched fields
    summary: str | None = None
    themes: list[str] | None = None
    key_verses: list[str] | None = None


class CrossReference(BaseModel):
    """Cross-reference between verses."""
    id: int | None = None
    from_reference: str
    to_reference: str
    votes: int = 0


class VerseInsight(BaseModel):
    """Pre-computed insight for a verse."""
    id: int | None = None
    reference: str
    explanation: str
    historical_context: str | None = None
    application: str | None = None
    cross_references: list[str] | None = None


class EmotionTag(BaseModel):
    """Emotion classification for a verse."""
    id: int | None = None
    reference: str
    emotions: list[str]  # ["hope", "comfort", "strength"]
    confidence: float
